/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://tm57ht3gbrcepg5k5satoswjcm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ux3j4iuouzdeddczpbdcp2muqu",
    "aws_cognito_identity_pool_id": "us-east-1:dbf09374-aae3-4216-aa84-895e78f2e0cf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jzg8OKo7H",
    "aws_user_pools_web_client_id": "6d5c7ui9na19cuhneloigsm2q6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER",
        "NAME",
        "PICTURE"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "smartseat-storage-43b115d3225556-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
