/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://npvawdtvqfa6fbtp6qm7eul4ni.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-meob2zfy5bef5prqk6t5jgn7tq",
    "aws_cognito_identity_pool_id": "us-east-1:9a759d52-cd6b-4086-ade3-95052f652ab6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PB78EgE5b",
    "aws_user_pools_web_client_id": "91cnd0mfn0mp75kfe3cplgif4",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER",
        "NAME",
        "PICTURE"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sse11114-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
